### PR TITLE
🔧 UPGRADE: PyYAML to v6

### PR DESCRIPTION
**Pull request by simkimsia**
## Description

PyYAML is now v6. So trying to upgrade it to v6

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have added an appropriate CHANGELOG entry

### CODE REVIEW

**Comment by simkimsia** [comment]
I have a project that relies on pattern-library and also using PyYAML. There's a conflict. Please upgrade PyYAML to v6

image

**Comment by simkimsia** [comment]
@bcdickinson  can help to review and merge this?

**Comment by simkimsia** [comment]
I receive an email abt the broken workflow run. Can teach me how to troubleshoot?

**Comment by thibaudcolas** [comment]
@simkimsia I believe this is the same error as we have on the main branch with Django’s dev branch, so nothing for you to worry about!

**Review by thibaudcolas — APPROVED** [review]
Thank you! I was surprised there wasn’t an update to our `poetry.lock`, but it looks like we have it intentionally ignored by git so all good.

**Comment by simkimsia** [comment]
@thibaudcolas could you still educate me how to run tests locally?

**Comment by thibaudcolas** [comment]
Sure – have a look at our [CONTRIBUTING](https://github.com/torchbox/django-pattern-library/blob/main/CONTRIBUTING.md) guidelines. We have three different ways to set up the project on there depending on your needs.

The simplest in my opinion is to use Poetry:

```
poetry install
poetry run ./runtests.py
```

**Pull request merged**
