### PR TITLE
Change header from Mikalab to Django Pattern Library

### PR DESCRIPTION
**Pull request by helenb**
## Description

Removes 'Mikalab' branding and instead uses 'Django Pattern Library'

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by chris-lawton** [comment]
Looks good. Wonder if we should update the screenshot used in the readme as well?

**Comment by helenb** [comment]
Thanks Chris, good idea re the image. I've updated it in the github settings - https://github.com/torchbox/django-pattern-library/settings - but it doesn't seem to have updated in the readme - do you know how to change that?

**Comment by chris-lawton** [comment]
Hmm, i think the one in settings is just for social media. Are you able to edit the `readme.md` file directly?

**Comment by tomdyson** [comment]
`README.md` line 8

**Comment by helenb** [comment]
Thanks Tom. I can see the link to the screenshot in the version of the README on github itself, but not in my local version. Also, the file is linked as

Screenshot of the pattern library UI, with navigation, pattern rendering, and configuration

How do I update that file? It's not in the repo so must be in the github settings somewhere.

**Comment by helenb** [comment]
My local build clearly wasn't up to date. I've now pushed a commit to update the screenshot.

**Pull request merged**
